using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eBanking.Models
{
    public class ViewModels
    {
    }
    public class RegisteredUserStatusViewModel
    {
        public List<Transaction> TopUp { get; set; }
        public List<Transaction> MoneyTransfer { get; set; }
        public List<Transaction> CreditTransfer { get; set; }
        public decimal? MoneyTransferIn { get; set; }
        public decimal? MoneyTransferOut { get; set; }
        public decimal? TopUpPrePaid { get; set; }
        public decimal? TopUpPostPaid { get; set; }
        public IEnumerable<Transaction> TransactionHistory { get; set; }
        public bool? IsDistributor { get; set; }
        public DistributorUserSummaryViewModel DistributorSummary { get; set; }
    }
    public class DistributorUserSummaryViewModel
    {
        public decimal? LastCommissionReturnAmount { get; set; }
        public DateTime? LastCommissionReturnTime { get; set; }
        public decimal? DistributorBalance { get; set; }
        public List<PinAssignViewModel> PinList { get; set; }
    }
    public class CancelTransaction
    {
        public int Id { get; set; }
    }
    public class GetTransferHistoryVM
    {
        public string UserName { get; set; }
        public int? Month { get; set; }
        public int? Year { get; set; }
    }

    public class ChangeUserPasswordVM
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Id { get; set; }

        [Required]
        public string NewPassword { get; set; }

        public bool? AutoGenerated { get; set; }

        public bool? SendSms { get; set; }
    }

    public class PendingMoneyTransfer
    {
        public int TransactionId { get; set; }
        public string UserId { get; set; }
        //public string OperationNumber { get; set; }
        //public string CurrencyISO { get; set; }
        public decimal? InsertedAmount { get; set; }
        public decimal? AmountOut { get; set; }
        public string ToUser { get; set; }
        public string ServiceName { get; set; }
        public int? Status { get; set; }
        public string ReferenceId { get; set; }
    }

    public class VendorReceivingConfirmation
    {
        public int ReqId { get; set; }
        public string Type { get; set; }
        public int VendorId { get; set; }
    }

    public class updatePendingMoneyTransfer
    {
        public updatePendingMoneyTransfer()
        {
            list = new List<PendingMoneyTransfer>();
        }
        public List<PendingMoneyTransfer> list { get; set; }
        public int ReqId { get; set; }
    }

    public class SMSToUser
    {
        public SMSToUser()
        {
            Valid = false;
            CountryCode = "";
            PhoneNumber = "";
            IsPostPaid = false;
            OperatorPrefix = "";
        }
        public bool Valid { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsPostPaid { get; set; }
        public string OperatorPrefix { get; set; }
    }

    public class SMSResponse
    {
        public SMSResponse()
        {
            ApiStatus = 0;
        }
        public int Id { get; set; }
        public string UserName { get; set; }
        public int ApiStatus { get; set; }
        public string OperationNumber { get; set; }
        public string MessageBody { get; set; }
        public int ClientId { get; set; }
    }

    public class VerifyDistributorCommission
    {
        public int? ServiceId { get; set; }
        public decimal? MRP { get; set; }
        public bool? IsPercentage { get; set; }
        public decimal? AllowedCommission { get; set; }
    }
    public class ServiceCommonViewModel
    {
        public int ServiceId { get; set; }
        public int? ServiceParentId { get; set; }
        public string ServiceName { get; set; }
        public decimal? ServiceValue { get; set; }
        public int? ServiceType { get; set; }
        public int? RatePlanId { get; set; }
        public decimal? MRP { get; set; }
        public bool? MRPIsPercentage { get; set; }
        public decimal? ServiceChargePercentage { get; set; }
        public decimal? ServiceChargeDescrete { get; set; }
        public decimal? OtherCharge { get; set; }
        public int? DestinationId { get; set; }
        public string DestinationName { get; set; }
        public bool? IsGroup { get; set; }
        public decimal? ToUSD { get; set; }
        public List<DistributorServiceChargeVM> DistributorServiceCharges { get; set; }
    }
    public class DistributorServiceChargeVM
    {
        public DistributorServiceChargeVM()
        {
            DistributorId = ServiceId = 0;
            ServiceCharge = 0;
            IsPercentage = false;
        }
        public int DistributorId { get; set; }
        public int ServiceId { get; set; }
        public decimal? ServiceCharge { get; set; }
        public bool? IsPercentage { get; set; }
    }
}